import React from 'react'

const page = () => {
  return (
    <>
      <div className='min-h-screen'>

      </div>
    </>
  )
}

export default page

export const metadata = {
    title: "About Us - Who we are?",
    description: "Generated by create next app",
  };
