import { Plus_Jakarta_Sans } from 'next/font/google';
import "./globals.css";
import Navbar from '@/components/Navbar';
import Whatsapp from '@/components/Whatsapp';
import Footer from '@/components/Footer';
import AosComponent from '@/subcomponent/AosComponent';

const plusjakartsans = Plus_Jakarta_Sans({
  subsets:["latin"],
  weight: [ '400', "500", "600", "700", "800"],
  variable: "--font-plus-jakarta-sans"

})

export const metadata = {
  title: "Xonier Technology - Innovating Tomorrow",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${plusjakartsans.className} antialiased`}
      >
        <Navbar/>
        <Whatsapp/>
        <AosComponent/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
